import {
  agentItem,
  branchItem,
  businessHours,
  footerContent,
  partnerItem,
  pageHeader,
  sectionIntro,
  seo,
  serviceItem,
  socialLinks,
  stepItem,
  trustBadge,
  whyChooseItem,
} from "./objects";
import {
  aboutPage,
  agentsPage,
  branchesPage,
  contactPage,
  homePage,
  servicesPage,
  siteSettings,
} from "./documents";
import { staffEmailAccount } from "./staffEmailAccount";

export const schemaTypes = [
  seo,
  pageHeader,
  sectionIntro,
  businessHours,
  socialLinks,
  footerContent,
  trustBadge,
  whyChooseItem,
  stepItem,
  serviceItem,
  partnerItem,
  branchItem,
  agentItem,
  siteSettings,
  homePage,
  servicesPage,
  branchesPage,
  agentsPage,
  aboutPage,
  contactPage,
  staffEmailAccount,
];
